version: '3'

services:
    app:
        container_name: 'face-api-sample-application'
        build: ./app
        tty: true
        volumes:
            - ./app:/src
        working_dir: '/src'
        ports:
            - 8080:8080
        command: npm start